# This is the development docker compose file
services:
  elastic:
    container_name: elastic 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./elk/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    env_file:
      - ./elk/base_credentials/.env
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl 'localhost:9200/_cluster/health'"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 15s
  setup_kibana:
    container_name: setup_kibana
    # The elasticsearch image is only used because it has bash and curl preinstalled
    # and to avoid downloading a new image with those dependencies
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    env_file:
      - ./elk/base_credentials/.env
    mem_limit: 1073741824
    volumes:
      - ./elk/kibana/setKibanaCredentials.sh:/scripts/setKibanaCredentials.sh
    command: ["bash","-c", "/scripts/setKibanaCredentials.sh"]
    depends_on:
      elastic:
        condition: service_healthy
  kibana:
    container_name: kibana
    depends_on:
      elastic:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.7.0
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    mem_limit: 1073741824
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile.dev
    container_name: consumer
    env_file:
      - ./consumer/.env
    volumes:
      - ./consumer:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      elastic:
        condition: service_healthy
  db:
    image: postgres
    container_name: db
    env_file:
      - ./db/.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d note_saver"]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 10s
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl 'localhost:3333/health'"]
      interval: 15s
      timeout: 60s
      retries: 20
      start_period: 10s
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/config.json:/app/public/config.json
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl 'localhost:3000'"]
      interval: 15s
      timeout: 60s
      retries: 20
      start_period: 15s
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl-certs/cert.pem:/root/ssl-certs/cert.pem
      - ./ssl-certs/cert-key.pem:/root/ssl-certs/cert-key.pem
    ports:
      - 8080:8080
    depends_on:
      client:
        condition: service_healthy
volumes:
  db_data: {}
  elastic_data: {}
  kibana_data: {}
