FROM golang:1.23 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Disable cgo and set the target OS to Linux for a statically linked binary
RUN CGO_ENABLED=0 GOOS=linux go build -o consumer .

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/consumer .

COPY .env /app/.env

CMD ["/app/consumer"]
