Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4096"
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    config.vm.provision "shell", path: "provision.sh", env: {"IS_VAGRANT_PROVISIONING" => "true" }
end
  