---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/helmrelease.yaml

configMapGenerator:
  - name: db-init
    files:
      - init.sql=files/init.sql
    options:
      disableNameSuffixHash: true
