---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client
  # - db
  - rabbitmq
  - server
  # TODO: Move resources below to separate directories
  - helmrepository.yaml
  - ingress.yaml
