---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository.yaml
  - ingress.yaml
  # TODO: Move resources above to separate directories
  - client
  - db
  - rabbitmq
  - server
