apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
spec:
  interval: 1m # TODO: Delete me
  timeout: 1m
  chart:
    spec:
      chart: rabbitmq
      version: "12.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    configurationExistingSecret: rabbitmq-conf
    loadDefinition:
      enabled: true
      existingSecret: rabbitmq-definitions
    extraConfiguration: |
      load_definitions = /app/load_definition.json
    # command: ["sleep", "infinity"]