apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
spec:
  interval: 1m # TODO: Delete me
  timeout: 1m
  chart:
    spec:
      chart: elasticsearch
      version: "22.0.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    master:
      masterOnly: false
      replicaCount: 1
    data:
      replicaCount: 0
    coordinating:
      replicaCount: 0
    ingest:
      replicaCount: 0
    security:
      existingSecret: elastic-password
      tls:
        restEncryption: false
    global:
      kibanaEnabled: true
    kibana:
      elasticsearch:
        security:
          auth:
            enabled: true
            existingSecret: elastic-password
          tls:
            enabled: false