apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: server
spec:
  interval: 5m
  chart:
    spec:
      chart: notesaver-service
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: elober-charts
        namespace: flux-system
  values:
    nameOverride: "server"
    image:
      repository: "elober/notesaver-server"
      pullPolicy: IfNotPresent
      tag: "latest"
    replicaCount: 1
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /health
        port: http
    readinessProbe:
      exec:
        command:
          - sh
          - -c
          - |
            nc -z -w 5 postgresql 5432 && nc -z -w 5 rabbitmq 5672
    envFrom:
      - configMapRef:
          name: server-env
    service:
      enabled: true
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: "minikube.server.notesaver"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - "minikube.server.notesaver"
          secretName: notesaver-tls
