apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: server
spec:
  interval: 5m
  chart:
    spec:
      chart: notesaver-service
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: elober-charts
        namespace: flux-system
  values:
    nameOverride: "server"
    image:
      repository: "elober/notesaver-server"
      pullPolicy: IfNotPresent
      tag: "latest"
    replicaCount: 1
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /health
        port: http
    readinessProbe:
      httpGet:
        path: /health
        port: http
    envFrom:
      - configMapRef:
          name: server-env
    service:
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: "minikube.server.notesaver"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - "minikube.server.notesaver"
          secretName: notesaver-tls
