---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/helmrelease.yaml

configMapGenerator:
  - name: client-config
    files:
      - config.json=files/config.json
    options:
      disableNameSuffixHash: true
