apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.4.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    prometheus:
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
      ingress:
        enabled: true
        ingressClassName: "nginx"
        ## Redirect ingress to an additional defined port on the service
        # servicePort: 8081
        hosts:
          - minikube.prometheus.notesaver

        ## Paths to use for ingress rules - one path should match the prometheusSpec.routePrefix
        ##
        paths:
        - /
        pathType: ImplementationSpecific
        tls:
          - secretName: notesaver-tls
            hosts:
              - minikube.prometheus.notesaver


    additionalPrometheusRulesMap:
       notesaver-alerts:
        groups:
          - name: pod-crashloop-alerts
            rules:
              - alert: PodCrashLooping
                expr: |
                  kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace="note-saver"} > 0
                for: 2m
                labels:
                  severity: warning
                annotations:
                  summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in CrashLoopBackOff"
                  description: "Container {{ $labels.container }} in pod {{ $labels.pod }} (namespace {{ $labels.namespace }}) is crashing repeatedly."
