apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: client
spec:
  interval: 5m
  chart:
    spec:
      chart: notesaver-service
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: elober-charts
        namespace: flux-system
  values:
    nameOverride: "client"
    image:
      repository: "elober/notesaver-client"
      pullPolicy: IfNotPresent
      tag: "latest"
    replicaCount: 1
    securityContext:
      runAsUser: 101
      runAsGroup: 101
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      exec:
        command:
          - sh
          - -c
          - 'curl -sf http://server:80/health'
    volumeMounts:
    - name: client-config-volume
      mountPath: /usr/share/nginx/html/config.json
      subPath: config.json
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: run-dir
      mountPath: /run
    volumes:
    - name: client-config-volume
      configMap:
        name: client-config
    - name: nginx-cache
      emptyDir: {}
    - name: run-dir
      emptyDir: {}
    service:
      enabled: true
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: "minikube.notesaver"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - "minikube.notesaver"
          secretName: notesaver-tls
