apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: client
spec:
  interval: 5m
  chart:
    spec:
      chart: notesaver-service
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: elober-charts
        namespace: flux-system
  values:
    nameOverride: "client"
    image:
      repository: "elober/notesaver-client"
      pullPolicy: IfNotPresent
      tag: "latest"
    replicaCount: 1
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    volumeMounts:
    - name: client-config-volume
      mountPath: /usr/share/nginx/html/config.json
      subPath: config.json
    volumes:
    - name: client-config-volume
      configMap:
        name: client-config
    service:
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: "minikube.notesaver"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - "minikube.notesaver"
          secretName: notesaver-tls
