---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - resources/server-deployment.yaml
  # - resources/server-service.yaml
  - resources/helmrelease.yaml

configMapGenerator:
  - name: server-env
    envs:
      - files/.env
    options:
      disableNameSuffixHash: true
