---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/server-deployment.yaml
  - resources/server-service.yaml

configMapGenerator:
  - name: server-env
    files:
      - .env=files/.env
