apiVersion: v1
kind: Service
metadata:
  name: notesaver-consumer
  labels:
    app: notesaver-consumer
spec:
  selector:
    app: notesaver-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
