apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: consumer
spec:
  interval: 5m
  chart:
    spec:
      chart: notesaver-service
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: elober-charts
        namespace: flux-system
  values:
    nameOverride: "consumer"
    image:
      repository: "elober/notesaver-consumer"
      pullPolicy: IfNotPresent
      tag: "latest"
    replicaCount: 1
    resources:
      requests:
        memory: "125Mi"
        cpu: "0.25"
      limits:
        memory: "250Mi"
        cpu: "0.5"
    livenessProbe:
      httpGet:
        path: /health
        port: http
    readinessProbe:
      httpGet:
        path: /health
        port: http
    envFrom:
      - configMapRef:
          name: consumer-env
    service:
      enabled: false
