apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  timeout: 1m
  chart:
    spec:
      chart: rabbitmq
      version: "16.0.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    configurationExistingSecret: rabbitmq-conf
    loadDefinition:
      enabled: true
      existingSecret: rabbitmq-definitions
