---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - resources/consumer-deployment.yaml
  # - resources/consumer-service.yaml
  - resources/helmrelease.yaml

configMapGenerator:
  - name: consumer-env
    envs:
      - files/.env
    options:
      disableNameSuffixHash: true
