---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/consumer-deployment.yaml
  - resources/consumer-service.yaml

configMapGenerator:
  - name: server-env
    envs:
      - files/.env
