nameOverride: "client"
image:
  repository: "elober/notesaver-client"
  pullPolicy: IfNotPresent
  tag: "latest"
replicaCount: 1
resources:
  requests:
    memory: "0.5Gi"
    cpu: "0.5"
  limits:
    memory: "1Gi"
    cpu: "1"
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  exec:
    command:
      - sh
      - -c
      - 'curl -sf http://server:80/health'
volumeMounts:
- name: client-config-volume
  mountPath: /usr/share/nginx/html/config.json
  subPath: config.json
volumes:
- name: client-config-volume
  configMap:
    name: client-config
service:
  enabled: true
  port: 80
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "minikube.notesaver"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "minikube.notesaver"
      secretName: notesaver-tls
