name: Auto Create Pull Request

on:
  create:
    branches:
      - '*'

permissions:
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add initial commit if branch has no commits
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Check if the branch has no unique commits compared to master
          if git diff --quiet origin/master..origin/$BRANCH_NAME; then
            echo "Branch already has commits, skipping initial commit."
          else
            echo "Branch has no commits, creating an empty initial commit..."
            git commit --allow-empty -m "Initial automatic empty commit for PR creation"
            git push origin $BRANCH_NAME
          fi

      - name: Create Pull Request
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          gh pr create --title "PR for ${BRANCH_NAME}" --body "PR generated from Git Action" --base master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
